# Generated by Django 6.0.1 on 2026-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('suggested_reply', models.TextField(blank=True)),
                ('is_important', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
