# Generated by Django 6.0.1 on 2026-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='gmail_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
