# Generated by Django 6.0.1 on 2026-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
